# Web Scraping
### Website: https://www.masslandrecords.com/suffolk/default.aspx

In [1]:
### Import packages
import requests
import bs4
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import time
from selenium.common.exceptions import NoSuchElementException

### Try use request --- unsuccessful

In [3]:
url = "https://www.masslandrecords.com/suffolk/default.aspx"
server_response = requests.get(url)
server_response

### Try use Selenium --- successful

In [ ]:
# Grantee
# Define the XPath for the table rows containing the people's information
xpath_base = "/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[5]/td/table/tbody/tr[2]/td[1]/div/div/table/tbody/tr"

# Get the total number of rows in the table
total_rows = len(driver.find_elements(By.XPATH, f"{xpath_base}"))

# Iterate through each row and check if the person is a grantee
for i in range(2, total_rows + 1):
    xpath_grantee = f"{xpath_base}[{i}]/td[2]"
    grantee_name = driver.find_element(By.XPATH, xpath_grantee).text

    if grantee_name == 'Grantee':
        xpath_name = f"{xpath_base}[{i}]/td[1]/a"
        name = driver.find_element(By.XPATH, xpath_name).text
        print("Grantee Name:", name)

In [90]:
driver = webdriver.Chrome("/path/to/chromedriver")
driver.implicitly_wait(10)
driver.get("https://www.masslandrecords.com/suffolk/default.aspx")

# 1. Get the current window handle
current_window = driver.current_window_handle

# Click on "Search Criteria"
driver.find_element(By.LINK_TEXT, 'Search Criteria').click()

# Click on "Recorded Date Search"
driver.find_element(By.LINK_TEXT, 'Recorded Date Search').click()

# Get all window handles
all_handles = driver.window_handles

# Find the ID field and clear its content
id_field = driver.find_element(By.ID, 'SearchFormEx1_ACSTextBox_DateFrom')
id_field.clear()

# Add '5/31/2023' to the ID field
id_field.send_keys('5/31/2023')  

# Find the ID field and clear its content
id_field1 = driver.find_element(By.ID, 'SearchFormEx1_ACSTextBox_DateTo')
id_field1.clear()

# Add '6/7/2023' to the ID field
id_field1.send_keys('6/7/2023')

# Select "DEED" from the dropdown
dropdown = Select(driver.find_element(By.ID, 'SearchFormEx1_ACSDropDownList_DocumentType'))
dropdown.select_by_visible_text('DEED')

# Click on "Search"
driver.find_element(By.ID, 'SearchFormEx1_btnSearch').click()

# Click on '100/pages'
driver.find_element(By.ID, 'DocList1_PageView100Btn').click()

# Click on 'Page2'
driver.find_element(By.ID, 'DocList1_ctl02_ctl02_LinkButtonNumber').click()

# Find the element by ID
lis_date = []
lis_type = []
lis_town = []
lis_doc = []
lis_price = []

for i in range(100):
    if i <= 7:
        element = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Rec. Date_" + str(i))
        lis_date.append(element.text)
        element1 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Type Desc._" + str(i))
        lis_type.append(element1.text)
        element2 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Town_" + str(i))
        lis_town.append(element2.text)
        element3 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Doc. #_" + str(i))
        lis_doc.append(element3.text)
        element.click()  # Click on the record date element
        time.sleep(1)  # Pause for 1 seconds
        # Find the table row (tr) element after clicking on the record date element
        tr_element = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
        # Find the td elements within the tr element
        td_elements = tr_element.find_elements(By.XPATH,"./td")
        # Get the individual values from the td elements
        values = [td.text for td in td_elements]
        # Add the price value
        lis_price.append(values[-2])
    else:
        element = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Rec. Date_" + str(i))
        lis_date.append(element.text)
        element1 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Type Desc._" + str(i))
        lis_type.append(element1.text)
        element2 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Town_" + str(i))
        lis_town.append(element2.text)
        element3 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Doc. #_" + str(i))
        lis_doc.append(element3.text)
        element.click()  # Click on the record date element
        time.sleep(1)  # Pause for 1 seconds
        # Find the table row (tr) element after clicking on the record date element
        tr_element = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
        # Find the td elements within the tr element
        td_elements = tr_element.find_elements(By.XPATH,"./td")
        # Get the individual values from the td elements
        values = [td.text for td in td_elements]
        # Add the price value
        lis_price.append(values[-2])

# Create a DataFrame 
df_information = pd.DataFrame({"Date": lis_date})
df_information1 = pd.DataFrame({"Type": lis_type})
df_information2 = pd.DataFrame({"Town": lis_town})
df_information3 = pd.DataFrame({"Doc Number": lis_doc})
df_information4 = pd.DataFrame({"Price": lis_price})

# Concatenate the two DataFrames horizontally
df_combined = pd.concat([df_information, df_information1, df_information2, df_information3, df_information4], axis=1)

# Print the combined DataFrame
df_combined

/var/folders/39/p0rpjrxj68l4cbrkhyvw78fm0000gn/T/ipykernel_17886/681848549.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("/path/to/chromedriver")

         Date  Type      Town Doc Number      Price
0   5/31/2023  DEED    REVERE      32089       1.00
1   5/31/2023  DEED   CHELSEA      32110  601000.00
2   5/31/2023  DEED  WINTHROP      32145  715000.00
3   5/31/2023  DEED    REVERE      32169  769000.00
4   5/31/2023  DEED    BOSTON      32177       0.00
..        ...   ...       ...        ...        ...
95   6/5/2023  DEED    BOSTON      33792  920000.00
96   6/5/2023  DEED    BOSTON      33871  760000.00
97   6/5/2023  DEED    REVERE      33874       1.00
98   6/5/2023  DEED    BOSTON      33879       1.00
99   6/5/2023  DEED    BOSTON      33888      10.00

[100 rows x 5 columns]

In [502]:
driver = webdriver.Chrome("/path/to/chromedriver")
driver.implicitly_wait(10)
driver.get("https://www.masslandrecords.com/suffolk/default.aspx")

# 1. Get the current window handle
current_window = driver.current_window_handle

# Click on "Search Criteria"
driver.find_element(By.LINK_TEXT, 'Search Criteria').click()

# Click on "Recorded Date Search"
driver.find_element(By.LINK_TEXT, 'Recorded Date Search').click()

# Get all window handles
all_handles = driver.window_handles

# Find the ID field and clear its content
id_field = driver.find_element(By.ID, 'SearchFormEx1_ACSTextBox_DateFrom')
id_field.clear()

# Add '5/31/2023' to the ID field
id_field.send_keys('3/24/2023')  

# Find the ID field and clear its content
id_field1 = driver.find_element(By.ID, 'SearchFormEx1_ACSTextBox_DateTo')
id_field1.clear()

# Add '6/7/2023' to the ID field
id_field1.send_keys('5/31/2023')

# Select "DEED" from the dropdown
dropdown = Select(driver.find_element(By.ID, 'SearchFormEx1_ACSDropDownList_DocumentType'))
dropdown.select_by_visible_text('DEED')

# Click on "Search"
driver.find_element(By.ID, 'SearchFormEx1_btnSearch').click()

# Click on '100/pages'
driver.find_element(By.ID, 'DocList1_PageView100Btn').click()

# Click on 'Page2'
driver.find_element(By.ID, 'DocList1_ctl02_ctl18_LinkButtonNumber').click()
time.sleep(2)

# Find the element by ID
lis_date = []
lis_type = []
lis_town = []
lis_doc = []
lis_price = []
lis_street = []
lis_description = []
lis_grantee = []

for i in range(46):
    try:
        if i <= 7:
            element = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Rec. Date_" + str(i))
            lis_date.append(element.text)
            element1 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Type Desc._" + str(i))
            lis_type.append(element1.text)
            element2 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Town_" + str(i))
            lis_town.append(element2.text)
            element3 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Doc. #_" + str(i))
            lis_doc.append(element3.text)
            element.click()  # Click on the record date element
            time.sleep(2)  # Pause for 2 seconds
            # Find the table row (tr) element after clicking on the record date element
            tr_element = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
            # Find the td elements within the tr element
            td_elements = tr_element.find_elements(By.XPATH,"./td")
            # Get the individual values from the td elements
            values = [td.text for td in td_elements]
            # Add the price value
            lis_price.append(values[-2])
            # Find the table row (tr) element
            tr_element1 = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[2]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
            # Find the td elements within the tr element
            td_elements1 = tr_element1.find_elements(By.XPATH,"./td")
            # Get the individual values from the td elements
            values1 = [td.text for td in td_elements1]
            # Add the address and description value
            lis_street.append(values1[1] + ' ' + values1[0])
            lis_description.append(values1[2])
            # Define the XPath for the table rows containing the people's information
            xpath_base = "/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[5]/td/table/tbody/tr[2]/td[1]/div/div/table/tbody/tr"
            # Get the total number of rows in the table
            total_rows = len(driver.find_elements(By.XPATH, f"{xpath_base}"))
            # Initialize an empty list to store the grantee names
            grantee_names = []
            # Iterate through each row and check if the person is a grantee
            for i in range(2, total_rows + 1):
                xpath_grantee = f"{xpath_base}[{i}]/td[2]"
                grantee_name = driver.find_element(By.XPATH, xpath_grantee).text

                if grantee_name == 'Grantee':
                    xpath_name = f"{xpath_base}[{i}]/td[1]/a"
                    name = driver.find_element(By.XPATH, xpath_name).text
                    grantee_names.append(name)

            # Merge the grantee names together with a comma separator
            merged_names = ",".join(grantee_names)
            lis_grantee.append(merged_names)
        else:
            element = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Rec. Date_" + str(i))
            lis_date.append(element.text)
            element1 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Type Desc._" + str(i))
            lis_type.append(element1.text)
            element2 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Town_" + str(i))
            lis_town.append(element2.text)
            element3 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Doc. #_" + str(i))
            lis_doc.append(element3.text)
            element.click()  # Click on the record date element
            time.sleep(2)  # Pause for 2 seconds
            # Find the table row (tr) element after clicking on the record date element
            tr_element = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
            # Find the td elements within the tr element
            td_elements = tr_element.find_elements(By.XPATH,"./td")
            # Get the individual values from the td elements
            values = [td.text for td in td_elements]
            # Add the price value
            lis_price.append(values[-2])
            # Find the table row (tr) element
            tr_element1 = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[2]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
            # Find the td elements within the tr element
            td_elements1 = tr_element1.find_elements(By.XPATH,"./td")
            # Get the individual values from the td elements
            values1 = [td.text for td in td_elements1]
            # Add the address and description value
            lis_street.append(values1[1] + ' ' + values1[0])
            lis_description.append(values1[2])
            # Define the XPath for the table rows containing the people's information
            xpath_base = "/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[5]/td/table/tbody/tr[2]/td[1]/div/div/table/tbody/tr"
            # Get the total number of rows in the table
            total_rows = len(driver.find_elements(By.XPATH, f"{xpath_base}"))
            # Initialize an empty list to store the grantee names
            grantee_names = []
            # Iterate through each row and check if the person is a grantee
            for i in range(2, total_rows + 1):
                xpath_grantee = f"{xpath_base}[{i}]/td[2]"
                grantee_name = driver.find_element(By.XPATH, xpath_grantee).text

                if grantee_name == 'Grantee':
                    xpath_name = f"{xpath_base}[{i}]/td[1]/a"
                    name = driver.find_element(By.XPATH, xpath_name).text
                    grantee_names.append(name)

            # Merge the grantee names together with a comma separator
            merged_names = ",".join(grantee_names)
            lis_grantee.append(merged_names)
    except NoSuchElementException:
        # Skip this record if element not found
        continue

# Create a DataFrame 
df_information = pd.DataFrame({"Date": lis_date})
df_information1 = pd.DataFrame({"Type": lis_type})
df_information2 = pd.DataFrame({"Town": lis_town})
df_information3 = pd.DataFrame({"Doc Number": lis_doc})
df_information4 = pd.DataFrame({"Price": lis_price})
df_information5 = pd.DataFrame({"Street": lis_street})
df_information6 = pd.DataFrame({"Address Description": lis_description})
df_information7 = pd.DataFrame({"Grantee Name(s)": lis_grantee})

# Concatenate the two DataFrames horizontally
df_combined = pd.concat([df_information, df_information1, df_information2, df_information3, df_information4,\
                        df_information5, df_information6, df_information7], axis=1)

# Print the combined DataFrame
df_combined

/var/folders/39/p0rpjrxj68l4cbrkhyvw78fm0000gn/T/ipykernel_17886/524928542.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("/path/to/chromedriver")

,Date,Type,Town,Doc Number,Price,Street,Address Description,Grantee Name(s)
0,5/30/2023,DEED,BOSTON,31824,515000.00,SEARLE RD 43,WEST ROXBURY,SEARLE ROAD LLC 43
1,5/30/2023,DEED,BOSTON,31838,663000.00,MURDOCK ST 108,BRIGHTON,LEUNG BRIAN
2,5/30/2023,DEED,BOSTON,31842,750000.00,SHELBY ST 22-24,EAST BOSTON,BRAZ REALTY GROUP LLC
3,5/30/2023,DEED,BOSTON,31846,1.00,HAYNES ST 64,EAST BOSTON,SPOLDI FRANCESCO C
4,5/30/2023,DEED,WINTHROP,31855,1.00,MYRTLE AVE 24,,"SUSAN E CASTELLA LIVING TRUST,CASTELLA SUSAN E"
5,5/30/2023,DEED,BOSTON,31857,1.00,WEST ST 64,HYDE PARK,"LACATTE LESLEY,FRANCOIS PATRICK,JORDAN NATHANI..."
6,5/30/2023,DEED,BOSTON,31874,1581000.00,PARK ST 55,CHARLESTOWN,"CHENEA EDWARD L,CIARIMBOLI JENNIFER A"
7,5/30/2023,DEED,BOSTON,31880,1.00,HAVRE ST 236,EAST BOSTON,PENZEL MAXWELL C
8,5/30/2023,DEED,REVERE,31936,1.00,ARCADIA ST 7,,"SANTILLI JOHN,JOHN SANTILLI REVOCABLE TRUST"
9,5/30/2023,DEED,BOSTON,31941,10.00,MOSS HILL RD 97,JAMAICA PLAIN,"MOSS HILL ROAD REALTY TRUST 97,GEORGOUNTZOS AG..."
10,5/30/2023,DEED,BOSTON,31954,1825000.00,WAVERLY ST 65,BRIGHTON,BRUNSON HOUSE INC
11,5/30/2023,DEED,BOSTON,31970,950000.00,SAWYER AVE 59,DORCHESTER,"REYNOLDS BRIAN,REYNOLDS MICHAEL"
12,5/30/2023,DEED,BOSTON,31996,995000.00,COLUMBIA RD 28,DORCHESTER,JAVIER YANNETTE R
13,5/30/2023,DEED,BOSTON,32006,1010000.00,BELLEVUE ST 205,WEST ROXBURY,CPAC CONTRACTING SERVICES
14,5/30/2023,DEED,CHELSEA,32045,860000.00,JOHN ST 14,,"AREIZA LUISA F,YEPES CARLOS S"
15,5/31/2023,DEED,REVERE,32089,1.00,SCHOOL ST 247,,VENDITTO MICHAEL
16,5/31/2023,DEED,CHELSEA,32110,601000.00,GARFIELD AVE 156,,"ALAS PACHECO JUAN J,PORTILLO MALDONADO LEIDY A"
17,5/31/2023,DEED,WINTHROP,32145,715000.00,BEACH RD 55,,"PUCKETT MICHAEL S,PUCKETT KARA"
18,5/31/2023,DEED,REVERE,32169,769000.00,WINTHROP PKWY 119,,"MALDONADO SANTOS O,CHACON MARITZA B"
19,5/31/2023,DEED,BOSTON,32177,0.00,HUTCHINGS ST 95-97,,XZ GRANT AND COMPANY LLC
20,5/31/2023,DEED,BOSTON,32178,1.00,HALE ST 10,,LXA AND COMPANY LLC
21,5/31/2023,DEED,BOSTON,32234,1600000.00,E SIXTH ST 693-695,,NASAR LLC
22,5/31/2023,DEED,BOSTON,32259,745000.00,CLEMENT AVE 4,WEST ROXBURY,CLEMENT AVENUE LLC 4
23,5/31/2023,DEED,BOSTON,32275,875000.00,STRATFORD ST 256,WEST ROXBURY,"SAUER SCOTT,MERINO AMY C"
24,5/31/2023,DEED,REVERE,32283,509900.00,MARTIN ST 31,,"MEDINA WILFREDO A,CADIZ CARMEN A"
25,5/31/2023,DEED,BOSTON,32290,755000.00,ROZELLA ST 7,DORCHESTER,"WEISS-IRVIN DAVID R,DOCKERY SHEKEIMA A"
26,5/31/2023,DEED,BOSTON,32307,825000.00,DORCHESTER AVE 833,DORCHESTER,GEORGE DOUGLAS R
27,5/31/2023,DEED,BOSTON,32316,710000.00,CENTRE ST 2314,WEST ROXBURY,FORGIONE BRIAN
28,5/31/2023,DEED,BOSTON,32320,1840000.00,I ST 181,SOUTH BOSTON,"GHOSHROY RITTICK,HUNTOON VIRGINIA L"
29,5/31/2023,DEED,CHELSEA,32330,781000.00,SHAWMUT ST 120,,"RAMIREZ SILVIA J P,LOPRETO HANSEL F V,MARTINEZ..."
30,5/31/2023,DEED,BOSTON,32343,800000.00,GLENWOOD AVE 22-24,HYDE PARK,ERJ REALTY LLC
31,5/31/2023,DEED,CHELSEA,32346,835000.00,GILLOOLY RD 41,,"HOSSAIN MOHAMMAD,ISLAM JAHADUL"
32,5/31/2023,DEED,BOSTON,32350,545000.00,DIETZ RD 33,HYDE PARK,JIMENEZ DENISE
33,5/31/2023,DEED,BOSTON,32363,1.00,POPLAR ST 394,ROSLINDALE,"DEBORAH A DUNLAP FAMILY TRUST,DUNLAP DEBORAH A..."
34,5/31/2023,DEED,BOSTON,32398,619000.00,BENNINGTON ST 1203,EAST BOSTON,"CARDONA DIEGO M,MEDINA MARIANA M"
35,5/31/2023,DEED,BOSTON,32419,672500.00,CROCKETT AVE 11,DORCHESTER,"KOSAK DEIRDRE C,KOSAK JOHN A"
36,5/31/2023,DEED,BOSTON,32449,290000.00,HOSMER ST 11,,MELVIN MEGHAN C
37,5/31/2023,DEED,BOSTON,32479,1300000.00,HIGH ST 32,CHARLESTOWN,HIGH LLC 32
38,5/31/2023,DEED,BOSTON,32489,761000.00,ZELLER ST 29,ROSLINDALE,"KELTING MARY W,RUNGE STEVEN C"
39,5/31/2023,DEED,WINTHROP,32552,780000.00,VILLA AVE 19,,"DISSTON NATALIE,TREPICCHIO COLIN"
40,5/31/2023,DEED,REVERE,32558,200000.00,DEDHAM ST 98,,LOT 98 DEDHHAM STREET REALTY TRUST
41,5/31/2023,DEED,CHELSEA,32586,1.00,GARLAND ST 74,,"LIBERMAN BEATRICE M,BEATRICE M LIBERMAN 2023 R..."
42,5/31/2023,DEED,BOSTON,32613,3400000.00,ST BOTOLPH ST 183,,PONDEROUS ORE LLC 183
43,5/31/2023,DEED,BOSTON,32616,960000.00,HILLVIEW AVE 11,ROSLINDALE,"PIZZI ANDREW J,AKRIVOULIS ANTHI"
44,5/31/2023,DEED,BOSTON,32632,990000.00,JEWETT ST 18,ROSLINDALE,"KAMONOU EMMANUEL M,KAMONOU EMMA J"
45,5/31/2023,DEED,BOSTON,32641,640000.00,HARVARD AVE 2,DORCHESTER,WILLIAMS CHAUNCEY

In [729]:
driver = webdriver.Chrome("/path/to/chromedriver")
driver.implicitly_wait(10)
driver.get("https://www.masslandrecords.com/suffolk/default.aspx")

# 1. Get the current window handle
current_window = driver.current_window_handle

# Click on "Search Criteria"
driver.find_element(By.LINK_TEXT, 'Search Criteria').click()

# Click on "Recorded Date Search"
driver.find_element(By.LINK_TEXT, 'Recorded Date Search').click()

# Get all window handles
all_handles = driver.window_handles

# Find the ID field and clear its content
id_field = driver.find_element(By.ID, 'SearchFormEx1_ACSTextBox_DateFrom')
id_field.clear()

# Add '5/31/2023' to the ID field
id_field.send_keys('5/24/2023')  

# Find the ID field and clear its content
id_field1 = driver.find_element(By.ID, 'SearchFormEx1_ACSTextBox_DateTo')
id_field1.clear()

# Add '6/7/2023' to the ID field
id_field1.send_keys('5/31/2023')

# Select "DEED" from the dropdown
dropdown = Select(driver.find_element(By.ID, 'SearchFormEx1_ACSDropDownList_DocumentType'))
dropdown.select_by_visible_text('UNIT DEED')

# Click on "Search"
driver.find_element(By.ID, 'SearchFormEx1_btnSearch').click()

# Click on '100/pages'
driver.find_element(By.ID, 'DocList1_PageView100Btn').click()

# Click on 'Page2'
driver.find_element(By.ID, 'DocList1_ctl02_ctl02_LinkButtonNumber').click()
time.sleep(2) 

# Find the element by ID
lis_date = []
lis_type = []
lis_town = []
lis_doc = []
lis_price = []
lis_street = []
lis_description = []
lis_grantee = []

for i in range(69):
    try:
        if i <= 7:
            element = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Rec. Date_" + str(i))
            lis_date.append(element.text)
            element1 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Type Desc._" + str(i))
            lis_type.append(element1.text)
            element2 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Town_" + str(i))
            lis_town.append(element2.text)
            element3 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl0" + str(2 + i) + "_ButtonRow_Doc. #_" + str(i))
            lis_doc.append(element3.text)
            element.click()  # Click on the record date element
            time.sleep(2)  # Pause for 2 seconds
            # Find the table row (tr) element after clicking on the record date element
            tr_element = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
            # Find the td elements within the tr element
            td_elements = tr_element.find_elements(By.XPATH,"./td")
            # Get the individual values from the td elements
            values = [td.text for td in td_elements]
            # Add the price value
            lis_price.append(values[-2])
            # Find the table row (tr) element
            tr_element1 = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[2]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
            # Find the td elements within the tr element
            td_elements1 = tr_element1.find_elements(By.XPATH,"./td")
            # Get the individual values from the td elements
            values1 = [td.text for td in td_elements1]
            # Add the address and description value
            lis_street.append(values1[1] + ' ' + values1[0])
            lis_description.append(values1[2])
            # Define the XPath for the table rows containing the people's information
            xpath_base = "/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[5]/td/table/tbody/tr[2]/td[1]/div/div/table/tbody/tr"
            # Get the total number of rows in the table
            total_rows = len(driver.find_elements(By.XPATH, f"{xpath_base}"))
            # Initialize an empty list to store the grantee names
            grantee_names = []
            # Iterate through each row and check if the person is a grantee
            for i in range(2, total_rows + 1):
                xpath_grantee = f"{xpath_base}[{i}]/td[2]"
                grantee_name = driver.find_element(By.XPATH, xpath_grantee).text

                if grantee_name == 'Grantee':
                    xpath_name = f"{xpath_base}[{i}]/td[1]/a"
                    name = driver.find_element(By.XPATH, xpath_name).text
                    grantee_names.append(name)

            # Merge the grantee names together with a comma separator
            merged_names = ",".join(grantee_names)
            lis_grantee.append(merged_names)
        else:
            element = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Rec. Date_" + str(i))
            lis_date.append(element.text)
            element1 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Type Desc._" + str(i))
            lis_type.append(element1.text)
            element2 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Town_" + str(i))
            lis_town.append(element2.text)
            element3 = driver.find_element(By.ID, "DocList1_GridView_Document_ctl" + str(2 + i) + "_ButtonRow_Doc. #_" + str(i))
            lis_doc.append(element3.text)
            element.click()  # Click on the record date element
            time.sleep(2)  # Pause for 2 seconds
            # Find the table row (tr) element after clicking on the record date element
            tr_element = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
            # Find the td elements within the tr element
            td_elements = tr_element.find_elements(By.XPATH,"./td")
            # Get the individual values from the td elements
            values = [td.text for td in td_elements]
            # Add the price value
            lis_price.append(values[-2])
            # Find the table row (tr) element
            tr_element1 = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[2]/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]")
            # Find the td elements within the tr element
            td_elements1 = tr_element1.find_elements(By.XPATH,"./td")
            # Get the individual values from the td elements
            values1 = [td.text for td in td_elements1]
            # Add the address and description value
            lis_street.append(values1[1] + ' ' + values1[0])
            lis_description.append(values1[2])
            # Define the XPath for the table rows containing the people's information
            xpath_base = "/html/body/form/div[4]/div[28]/div/div[2]/table/tbody/tr[5]/td/table/tbody/tr[2]/td[1]/div/div/table/tbody/tr"
            # Get the total number of rows in the table
            total_rows = len(driver.find_elements(By.XPATH, f"{xpath_base}"))
            # Initialize an empty list to store the grantee names
            grantee_names = []
            # Iterate through each row and check if the person is a grantee
            for i in range(2, total_rows + 1):
                xpath_grantee = f"{xpath_base}[{i}]/td[2]"
                grantee_name = driver.find_element(By.XPATH, xpath_grantee).text

                if grantee_name == 'Grantee':
                    xpath_name = f"{xpath_base}[{i}]/td[1]/a"
                    name = driver.find_element(By.XPATH, xpath_name).text
                    grantee_names.append(name)

            # Merge the grantee names together with a comma separator
            merged_names = ",".join(grantee_names)
            lis_grantee.append(merged_names)
    except NoSuchElementException:
        # Skip this record if element not found
        continue

# Create a DataFrame 
df_information = pd.DataFrame({"Date": lis_date})
df_information1 = pd.DataFrame({"Type": lis_type})
df_information2 = pd.DataFrame({"Town": lis_town})
df_information3 = pd.DataFrame({"Doc Number": lis_doc})
df_information4 = pd.DataFrame({"Price": lis_price})
df_information5 = pd.DataFrame({"Street": lis_street})
df_information6 = pd.DataFrame({"Address Description": lis_description})
df_information7 = pd.DataFrame({"Grantee Name(s)": lis_grantee})

# Concatenate the two DataFrames horizontally
df_combined = pd.concat([df_information, df_information1, df_information2, df_information3, df_information4,\
                        df_information5, df_information6, df_information7], axis=1)

# Print the combined DataFrame
df_combined

/var/folders/39/p0rpjrxj68l4cbrkhyvw78fm0000gn/T/ipykernel_17886/3154976102.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("/path/to/chromedriver")

,Date,Type,Town,Doc Number,Price,Street,Address Description,Grantee Name(s)
0,5/30/2023,UNIT DEED,BOSTON,31898,525000.00,ADAMS ST UNIT F109 & PKG SP 40 1241,,CARMODY ROBERT JR
1,5/30/2023,UNIT DEED,BOSTON,31906,250000.00,TERRACE ST UNIT 4 40,,AUDET JEANINE
2,5/30/2023,UNIT DEED,BOSTON,31913,2000000.00,BEACON ST UNIT 7 & PKG SP 6 122,,"MCCROSKERY PETER,MCCROSKERY ELLEN"
3,5/30/2023,UNIT DEED,BOSTON,31917,2275000.00,LOVEJOY WHARF UNIT 9D 100,,PEABODY TERRACE PARTNERS 2 LLC
4,5/30/2023,UNIT DEED,BOSTON,31920,576500.00,ROSEMONT ST UNIT 2 30,DORCHESTER,"ANGIER SELENE M,YEZUKEVICH JOSEPH A"
...,...,...,...,...,...,...,...,...
64,5/31/2023,UNIT DEED,BOSTON,32614,1.00,BOWEN ST UNIT 2 177,SOUTH BOSTON,SHAKEDOWN STREET LLC
65,5/31/2023,UNIT DEED,BOSTON,32628,710000.00,GREEN ST UNIT 2 54,JAMAICA PLAIN,"SLOSKY BRENT,SLOSKY CAMRYN"
66,5/31/2023,UNIT DEED,BOSTON,32638,680000.00,DORCHESTER ST UNIT 4 AND PKG SP 2 366,SOUTH BOSTON,"DESHPANDE SUPREET,DESHPANDE AAKASH"
67,5/31/2023,UNIT DEED,BOSTON,32646,692500.00,WALLEY ST UNIT 408 & PKG SP 4 11,EAST BOSTON,PHO ALEXANDER CHANG FUNG
68,5/31/2023,UNIT DEED,BOSTON,32650,1.00,W THIRD ST UNIT 135 135,SOUTH BOSTON,"ESSELE PETER,ESSELE SAMANTHA,ESSELE FAMILY REV..."

### The method we deal with abnormal values due to some elements' missing in some records

In [484]:
for i in range(0,45):
    df_combined.loc[i, 'Grantee_Updated'] = df_combined.loc[i, 'Grantee Name(s)']

for i in range(45,99):
    df_combined.loc[i + 1, 'Grantee_Updated'] = df_combined.loc[i, 'Grantee Name(s)']

In [485]:
df_combined['Grantee_Updated'][45]='GLENWAY ST LLC 145'

In [486]:
df_combined = df_combined.drop(columns=['Grantee Name(s)']).\
rename(columns={'Grantee_Updated':'Grantee Name(s)'})

In [496]:
for i in range(0,36):
    df_combined.loc[i, 'Grantee_Updated'] = df_combined.loc[i, 'Grantee Name(s)']
    df_combined.loc[i, 'Street_Updated'] = df_combined.loc[i, 'Street']
    df_combined.loc[i, 'Address_Updated'] = df_combined.loc[i, 'Address Description']

for i in range(36,99):
    df_combined.loc[i + 1, 'Grantee_Updated'] = df_combined.loc[i, 'Grantee Name(s)']
    df_combined.loc[i + 1, 'Street_Updated'] = df_combined.loc[i, 'Street']
    df_combined.loc[i + 1, 'Address_Updated'] = df_combined.loc[i, 'Address Description']

In [497]:
df_combined['Grantee_Updated'][36]='BP HANCOCK LLC'

In [498]:
df_combined = df_combined.drop(columns=['Grantee Name(s)','Street','Address Description']).\
rename(columns={'Grantee_Updated':'Grantee Name(s)',\
                'Street_Updated':'Street','Address_Updated':'Address Description'})

In [320]:
df_combined['Grantee_Updated'][27] = 'SPEAR JENNIFER M, CRITCH MATTHEW C, HARDE SUZANNE M, \
ODONNELL BRIAN J, GENOVESE JULIE P, DAIGLE CHRISTINA P, PENNEY ROBERT C JR, PARRINO GININE N, \
PENNEY ALBERT L, PENNEY SUSAN M'

In [323]:
df_combined = df_combined.drop(columns='Grantee Name(s)').\
rename(columns={'Grantee_Updated':'Grantee Name(s)'})

In [211]:
for i in range(1, 99):
    df_combined.loc[i + 1, 'Street_Updated'] = df_combined.loc[i, 'Street']
    df_combined.loc[i + 1, 'Address_Updated'] = df_combined.loc[i, 'Address Description']
    
for i in range(0,1):
    df_combined.loc[i, 'Street_Updated'] = df_combined.loc[i, 'Street']
    df_combined.loc[i, 'Address_Updated'] = df_combined.loc[i, 'Address Description']
    
for i in range(91, 98):
    df_combined.loc[i + 2, 'Grantee_Updated'] = df_combined.loc[i, 'Grantee Name(s)']
    
for i in range(0,1):
    df_combined.loc[i, 'Grantee_Updated'] = df_combined.loc[i, 'Grantee Name(s)']

for i in range(1,91):
    df_combined.loc[i + 1, 'Grantee_Updated'] = df_combined.loc[i, 'Grantee Name(s)']

In [224]:
df_combined = df_combined.drop(columns=['Grantee Name(s)','Street','Address Description']).\
rename(columns={'Grantee Name(s)_Updated':'Grantee Name(s)',\
                'Street_Updated':'Street','Address_Updated':'Address Description'})

### Store the DEED Housing price

In [503]:
df_final83 = pd.concat([df_final82, df_combined], axis=0).reset_index().drop(columns='index')
df_final83

,Date,Type,Town,Doc Number,Price,Street,Address Description,Grantee Name(s)
0,1/3/2022,DEED,BOSTON,48,1.00,ROSLIN ST 51A,DORCHESTER,"LEBRUN RICHARD G,SEREIGO-WAREING JAMES"
1,1/3/2022,DEED,WINTHROP,91,1.00,MOORE ST 64,,"CURTIN GREGORY D,STELLA KELSEY,MOORE STREET RE..."
2,1/3/2022,DEED,BOSTON,102,10.00,SWAN ST 14,EAST BOSTON,BENNINGTON STREET LLC 1201
3,1/3/2022,DEED,BOSTON,104,10.00,BENNINGTON ST 1201,EAST BOSTON,BENNINGTON STREET LLC 1201
4,1/3/2022,DEED,BOSTON,116,462500.00,KEITH ST 14,,R BROOKS INC
...,...,...,...,...,...,...,...,...
8150,5/31/2023,DEED,CHELSEA,32586,1.00,GARLAND ST 74,,"LIBERMAN BEATRICE M,BEATRICE M LIBERMAN 2023 R..."
8151,5/31/2023,DEED,BOSTON,32613,3400000.00,ST BOTOLPH ST 183,,PONDEROUS ORE LLC 183
8152,5/31/2023,DEED,BOSTON,32616,960000.00,HILLVIEW AVE 11,ROSLINDALE,"PIZZI ANDREW J,AKRIVOULIS ANTHI"
8153,5/31/2023,DEED,BOSTON,32632,990000.00,JEWETT ST 18,ROSLINDALE,"KAMONOU EMMANUEL M,KAMONOU EMMA J"
8154,5/31/2023,DEED,BOSTON,32641,640000.00,HARVARD AVE 2,DORCHESTER,WILLIAMS CHAUNCEY

In [504]:
df_final83.to_csv('Housing_DEED.csv')

### Store the UNIT DEED house information

In [730]:
df101 = pd.concat([df100, df_combined], axis=0).reset_index().drop(columns='index')
df101

,Date,Type,Town,Doc Number,Price,Street,Address Description,Grantee Name(s)
0,1/3/2022,UNIT DEED,BOSTON,40,100.00,HAROLD ST UNIT 3 139,,MBAH LLC
1,1/3/2022,UNIT DEED,BOSTON,44,1.00,ALBEMARLE ST UNIT 4 19,,"FOREVER RICH INVESTMENT LLC,SUCCESSGATE55 INVE..."
2,1/3/2022,UNIT DEED,BOSTON,76,1.00,TREMONT ST UNIT 1 589,,"RICE CHAD W,BUI LUANN"
3,1/3/2022,UNIT DEED,BOSTON,85,355000.00,QUINCY ST UNIT 1 37,DORCHESTER,HAILE MELAKU Z
4,1/3/2022,UNIT DEED,BOSTON,93,10.00,MEDFORD ST UNIT 490 486-490,CHARLESTOWN,"POMERANCE MITCHELL J,MITCHELL J POMERANCE LIVI..."
...,...,...,...,...,...,...,...,...
10011,5/31/2023,UNIT DEED,BOSTON,32614,1.00,BOWEN ST UNIT 2 177,SOUTH BOSTON,SHAKEDOWN STREET LLC
10012,5/31/2023,UNIT DEED,BOSTON,32628,710000.00,GREEN ST UNIT 2 54,JAMAICA PLAIN,"SLOSKY BRENT,SLOSKY CAMRYN"
10013,5/31/2023,UNIT DEED,BOSTON,32638,680000.00,DORCHESTER ST UNIT 4 AND PKG SP 2 366,SOUTH BOSTON,"DESHPANDE SUPREET,DESHPANDE AAKASH"
10014,5/31/2023,UNIT DEED,BOSTON,32646,692500.00,WALLEY ST UNIT 408 & PKG SP 4 11,EAST BOSTON,PHO ALEXANDER CHANG FUNG
10015,5/31/2023,UNIT DEED,BOSTON,32650,1.00,W THIRD ST UNIT 135 135,SOUTH BOSTON,"ESSELE PETER,ESSELE SAMANTHA,ESSELE FAMILY REV..."

In [731]:
df101.to_csv('Housing_UNITDEED.csv')

### Merge two datasets together to create the final housing dataset

In [732]:
dff = pd.concat([df_final83, df101], axis=0).reset_index().drop(columns='index')
dff

,Date,Type,Town,Doc Number,Price,Street,Address Description,Grantee Name(s)
0,1/3/2022,DEED,BOSTON,48,1.00,ROSLIN ST 51A,DORCHESTER,"LEBRUN RICHARD G,SEREIGO-WAREING JAMES"
1,1/3/2022,DEED,WINTHROP,91,1.00,MOORE ST 64,,"CURTIN GREGORY D,STELLA KELSEY,MOORE STREET RE..."
2,1/3/2022,DEED,BOSTON,102,10.00,SWAN ST 14,EAST BOSTON,BENNINGTON STREET LLC 1201
3,1/3/2022,DEED,BOSTON,104,10.00,BENNINGTON ST 1201,EAST BOSTON,BENNINGTON STREET LLC 1201
4,1/3/2022,DEED,BOSTON,116,462500.00,KEITH ST 14,,R BROOKS INC
...,...,...,...,...,...,...,...,...
18166,5/31/2023,UNIT DEED,BOSTON,32614,1.00,BOWEN ST UNIT 2 177,SOUTH BOSTON,SHAKEDOWN STREET LLC
18167,5/31/2023,UNIT DEED,BOSTON,32628,710000.00,GREEN ST UNIT 2 54,JAMAICA PLAIN,"SLOSKY BRENT,SLOSKY CAMRYN"
18168,5/31/2023,UNIT DEED,BOSTON,32638,680000.00,DORCHESTER ST UNIT 4 AND PKG SP 2 366,SOUTH BOSTON,"DESHPANDE SUPREET,DESHPANDE AAKASH"
18169,5/31/2023,UNIT DEED,BOSTON,32646,692500.00,WALLEY ST UNIT 408 & PKG SP 4 11,EAST BOSTON,PHO ALEXANDER CHANG FUNG
18170,5/31/2023,UNIT DEED,BOSTON,32650,1.00,W THIRD ST UNIT 135 135,SOUTH BOSTON,"ESSELE PETER,ESSELE SAMANTHA,ESSELE FAMILY REV..."

In [733]:
dff.to_csv('Housing_total.csv')